--5-1
create table STUDENT.EVACUATIONFACILITY1 as select * from STUDENT.EVACUATIONFACILITY ; 

update STUDENT.EVACUATIONFACILITY1
set EFCAPACITY = 5000
where ADDRESS = '苗栗縣竹南鎮和平街79號';

--5-2
delete from STUDENT.EVACUATIONFACILITY1
where EFCAPACITY < 1000;