--4-1
select PI.POLICESTATION as 轄管分局, PI.PTEL as 分局連絡電話
 from
    (select distinct PSERIAL
     from STUDENT.VILLAGEINFOR 
     where VSERIAL in(
        select VSERIAL
         from STUDENT.EVACUATIONFACILITY
         where EFCAPACITY > 1000)) PS
 left join STUDENT.POLICEINFOR PI
 on PS.PSERIAL = PI.PSERIAL;

--4-2
select PI.POLICESTATION as 轄管分局, PI.PTEL as 分局連絡電話, count(PI.PSERIAL) over (partition by PI.PSERIAL) as 避難設施大於1000容人數量的設施數量
 from STUDENT.EVACUATIONFACILITY EF
 left join STUDENT.VILLAGEINFOR VI
 on EF.VSERIAL = VI.VSERIAL
 left join STUDENT.POLICEINFOR PI
 on VI.PSERIAL = PI.PSERIAL
 where EFCAPACITY > 1000;
    
--4-3
select PI.POLICESTATION as 轄管分局, PI.PTEL as 分局連絡電話, VILLAGEINFOR.ADDRESS as 避難設施地址, BT.BUILDING, count(PI.PSERIAL) over (partition by PI.PSERIAL) as 避難設施大於1000容人數量的設施數量
 from STUDENT.EVACUATIONFACILITY EF
 left join STUDENT.BUILDINGTYPE BT
 on EVACUATIONFACILITY.EFTYPE = BUILDINGTYPE.BSERIAL
 left join STUDENT.VILLAGEINFOR VI
 on EF.VSERIAL = VI.VSERIAL
 left join STUDENT.POLICEINFOR PI
 on VI.PSERIAL = PI.PSERIAL
 where EFCAPACITY > 1000;
    
--4-4
select EF.SERIAL, VI.VSERIAL, EF.ADDRESS as 避難設施地址, EF.EFCAPACITY, PI.POLICESTAION, PI.PTEL as 分局連絡電話
 from STUDENT.EVACUATIONFACILITY EF
 left join STUDENT.VILLAGEINFOR VI
 on EF.VSERIAL = VI.VSERIAL
 left join STUDENT.POLICEINFOR PI
 on VI.PSERIAL = PI.PSERIAL
 where ADDRESS like '%中%';

--4-5
select EF.SERIAL, B.VILLAGE, B.VADDRESS as 村里辦公室位置, EF.ADDRESS as 避難設施地址, EF.EFCAPACITY
 from STUDENT.EVACUATIONFACILITY EF
 left join STUDENT.VILLAGEINFOR VI
 on EF.VSERIAL = VI.VSERIAL
 where EFTYPE in('G1', 'G2');

